---



- name: mariadb container
  docker_container:
    name: wp-mariadb
    image: library/mariadb
    state: started
    volumes:
      - /var/lib/mysql
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    restart_policy: unless-stopped
    
- name: wp container
  docker_container:
    name: wp-app
    image: library/wordpress
    state: started
    ports: 80:80
    links:
      - wp-mariadb:mysql
    env:
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    restart_policy: unless-stopped